version: '3.9'
services:
  postgres:
    image: postgres:13
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_DB=demoDB
      - POSTGRES_PASSWORD=pwd


  arango:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: pwd
    ports:
      - "8528:8529"

  redis:
    image: redis
    ports:
      - "8001:6379"

  app:
    image: 'zaychik/system-user-rest'
    environment:
      - PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/demoDB
      - SPRING_REDIS_HOST=redis
      - ARANGODB_HOST=arango
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - arango
      - redis
    links:
      - redis
      - arango
      - postgres

