version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_DB=demoDB
      - POSTGRES_PASSWORD=pwd
  arango:
    image: arangodb:latest
    container_name: arango
    environment:
      ARANGO_ROOT_PASSWORD: pwd
    ports:
      - "8528:8529"
  redis:
    image: redis
    container_name: redis
    ports:
      - "8001:6379"
  app:
    image: 'zaychik/system-user-rest'
    environment:
      - PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/demoDB
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - ARANGODB_HOST=arango
      - ARANGODB_PORT=8529
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - arango
      - redis
    links:
      - redis
      - arango
      - postgres